# Generated by Django 3.2.15 on 2023-07-04 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
