# Generated by Django 3.2.15 on 2023-07-05 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CLIENT', 'Client'), ('EMPLOYEE', 'Employee')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
