# Generated by Django 4.2.3 on 2023-07-11 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_delete_client_delete_employee_remove_user_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128),
        ),
    ]
