# Generated by Django 4.2.3 on 2023-07-12 16:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_service_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=django.utils.timezone.now, max_digits=6, verbose_name='price'),
            preserve_default=False,
        ),
    ]
