# Generated by Django 4.2.3 on 2023-07-12 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='precio',
        ),
    ]
