# Generated by Django 4.2.3 on 2023-07-25 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=255)),
                (
                    "day",
                    models.DateField(help_text="Dia de la cita", verbose_name="Day"),
                ),
                (
                    "timetable",
                    models.CharField(
                        choices=[
                            ("1", "08:00 a.m. - 08:30 a.m."),
                            ("2", "08:30 a.m. - 09:00 a.m."),
                            ("3", "09:00 a.m. - 09:30 a.m."),
                            ("4", "09:30 a.m. - 10:00 a.m."),
                            ("5", "10:00 a.m. - 10:30 a.m."),
                            ("6", "10:30 a.m. - 11:00 a.m."),
                            ("7", "11:00 a.m. - 11:30 a.m."),
                            ("8", "11:30 a.m. - 12:00 p.m."),
                            ("9", "12:00 p.m. - 12:30 p.m."),
                            ("10", "12:30 p.m. - 01:00 p.m."),
                            ("11", "01:00 p.m. - 01:30 p.m."),
                            ("12", "01:30 p.m. - 02:00 p.m."),
                            ("13", "02:00 p.m. - 02:30 p.m."),
                            ("14", "02:30 p.m. - 03:00 p.m."),
                            ("15", "03:00 p.m. - 03:30 p.m."),
                            ("16", "03:30 p.m. - 04:00 p.m."),
                            ("17", "04:00 p.m. - 04:30 p.m."),
                            ("18", "04:30 p.m. - 05:00 p.m."),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.service",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
