# Generated by Django 4.2.3 on 2023-07-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0004_alter_appointment_service_alter_appointment_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="timetable",
            field=models.CharField(
                choices=[
                    ("1", "08:00 to 08:30"),
                    ("2", "08:30 to 09:00"),
                    ("3", "09:00 to 09:30"),
                    ("4", "09:30 to 10:00"),
                    ("5", "10:00 to 10:30"),
                    ("6", "10:30 to 11:00"),
                    ("7", "11:00 to 11:30"),
                    ("8", "11:30 to 12:00"),
                    ("9", "12:00 to 12:30"),
                    ("10", "12:30 to 13:00"),
                    ("11", "13:00 to 13:30"),
                    ("12", "13:30 to 14:00"),
                    ("13", "14:00 to 14:30"),
                    ("14", "14:30 to 15:00"),
                    ("15", "15:00 to 15:30"),
                    ("16", "15:30 to 16:00"),
                    ("17", "16:00 to 16:30"),
                    ("18", "16:30 to 17:00"),
                    ("19", "17:00 to 17:30"),
                    ("20", "17:30 to 18:00"),
                ],
                max_length=10,
            ),
        ),
    ]
